      INTERFACE
!
!** WARNING: NEXT FUNCTION-NAME'S DATA TYPE DECLARATION IS INCOMPLETE!
      FUNCTION XRANG(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      REAL              ::  XRANG
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG
      END INTERFACE
! **********
      INTERFACE
      SUBROUTINE PUNISH(A,B,C)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      REAL(4)  , INTENT(INOUT) :: A
      REAL(4)  , INTENT(INOUT) :: B
      REAL(4)  , INTENT(INOUT) :: C
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END SUBROUTINE PUNISH
      END INTERFACE
! **********
      INTERFACE
!
      SUBROUTINE DUMMY
      USE A1
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END SUBROUTINE DUMMY
      END INTERFACE
! **********
      INTERFACE
!
      BLOCK DATA
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      INTERFACE
      FUNCTION XRANG1(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      REAL(4)              ::  XRANG1
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG1
      END INTERFACE
! **********
      INTERFACE
      FUNCTION XRANG2(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      REAL(8)              ::  XRANG2
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG2
      END INTERFACE
! **********
      INTERFACE
!** WARNING: NEXT FUNCTION-NAME'S DATA TYPE DECLARATION IS INCOMPLETE!
      FUNCTION XRANG3(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      COMPLEX              ::  XRANG3
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG3
      END INTERFACE
! **********
      INTERFACE
      FUNCTION XRANG4(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      COMPLEX(8)              ::  XRANG4
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG4
      END INTERFACE
! **********
      INTERFACE
      FUNCTION XRANG5(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      COMPLEX(16)              ::  XRANG5
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG5
      END INTERFACE
! **********
      INTERFACE
!** WARNING: NEXT FUNCTION-NAME'S DATA TYPE DECLARATION IS INCOMPLETE!
      FUNCTION XRANG6(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      DOUBLEÿCOMPLEX              ::  XRANG6
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG6
      END INTERFACE
! **********
      INTERFACE
!** WARNING: NEXT FUNCTION-NAME'S DATA TYPE DECLARATION IS INCOMPLETE!
      FUNCTION XRANG7(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      DOUBLEÿPRECISION              ::  XRANG7
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG7
      END INTERFACE
! **********
      INTERFACE
!** WARNING: NEXT FUNCTION-NAME'S DATA TYPE DECLARATION IS INCOMPLETE!
      FUNCTION XRANG7(X,XMIN,XMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      UNKNOWN              ::  XRANG7
      REAL(4)  , INTENT(INOUT) :: X
      REAL(4)  , INTENT(INOUT) :: XMIN
      REAL(4)  , INTENT(INOUT) :: XMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION XRANG7
      END INTERFACE
! **********
      INTERFACE
!** WARNING: NEXT FUNCTION-NAME'S DATA TYPE DECLARATION IS INCOMPLETE!
      FUNCTION IRANG0(I,IMIN,IMAX)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      UNKNOWN              ::  IRANG0
      INTEGER(4)  , INTENT(INOUT) :: I
      INTEGER(4)  , INTENT(INOUT) :: IMIN
      INTEGER(4)  , INTENT(INOUT) :: IMAX
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END FUNCTION IRANG0
      END INTERFACE
! **********
