      INTERFACE
!
      SUBROUTINE NPARSE(INNAME,BASNAM,LAST)
      IMPLICIT NONE
      INTEGER(2) :: IJKLMN, MYCDEF
! ** BEGIN  EZUP-GENERATED 'INTENT' STATEMENTS **
      CHARACTER(LEN=64)  , INTENT(INOUT) :: INNAME
      CHARACTER(LEN=24)  , INTENT(INOUT) :: BASNAM
      UNKNOWN, INTENT(INOUT) :: LAST
! ** END OF EZUP-GENERATED 'INTENT' STATEMENTS **
      END SUBROUTINE NPARSE
      END INTERFACE
! **********
