      MODULE DEFALT
      IMPLICIT NONE
! THE FOLLOWING VARIABLES WERE DETECTED. IT IS YOUR
! JOB TO BE SURE THAT THE 'UNKNOWN' TYPE DECLARATIONS ARE
! PROPERLY REVISED TO REFLECT CORRECT INFORMATION.
! ** NOTE : YOU MAY NEED TO DELETE SOME TYPE-DECLARATIONS FROM
! YOUR SOURCE FILE BECAUSE SOME MAY HAVE BEEN COPIED INTO THE
! MODULES.OUT FILE.
!
      REAL(4)          ::  ABCDE                            
      REAL(4)          ::  EWGDAS                           
      INTEGER(4)       ::  A1                               
      INTEGER(4)       ::  A3                               
      INTEGER(4)       ::  A6                               
      INTEGER(4)       ::  A7                               
      INTEGER(4)       ::  A8                               
      INTEGER(4)       ::  A9                               
      INTEGER(4)       ::  A11                              
      INTEGER(4)       ::  A12                              
! END LIST OF DETECTED COMMON BLOCK VARS.
      END MODULE DEFALT
!
      MODULE A1
      IMPLICIT NONE
! THE FOLLOWING VARIABLES WERE DETECTED. IT IS YOUR
! JOB TO BE SURE THAT THE 'UNKNOWN' TYPE DECLARATIONS ARE
! PROPERLY REVISED TO REFLECT CORRECT INFORMATION.
! ** NOTE : YOU MAY NEED TO DELETE SOME TYPE-DECLARATIONS FROM
! YOUR SOURCE FILE BECAUSE SOME MAY HAVE BEEN COPIED INTO THE
! MODULES.OUT FILE.
!
      INTEGER(4)       ::  K1MK23                           
      INTEGER(4)       ::  K1MK34                           
      INTEGER(4)       ::  K1MK56                           
! END LIST OF DETECTED COMMON BLOCK VARS.
      END MODULE A1
!
      MODULE TRASH
      IMPLICIT NONE
! THE FOLLOWING VARIABLES WERE DETECTED. IT IS YOUR
! JOB TO BE SURE THAT THE 'UNKNOWN' TYPE DECLARATIONS ARE
! PROPERLY REVISED TO REFLECT CORRECT INFORMATION.
! ** NOTE : YOU MAY NEED TO DELETE SOME TYPE-DECLARATIONS FROM
! YOUR SOURCE FILE BECAUSE SOME MAY HAVE BEEN COPIED INTO THE
! MODULES.OUT FILE.
!
! END LIST OF DETECTED COMMON BLOCK VARS.
      END MODULE TRASH
