      MODULE RENCOM
      IMPLICIT NONE
!     DATA & COMMON BLOCK DECLARATIONS FOR EZUP
!
      character(len=96) :: FNAME1, FNAME2
      CHARACTER(LEN=72) ::  CONBUF
      CHARACTER(LEN=1) :: LABEL(400,5,2),CLINE(1450),LABL(20,7)
      CHARACTER(LEN=4) :: KEYWDS(50)
      CHARACTER(LEN=1) ::  VARLST(400,16)
      CHARACTER(LEN=16) ::  NMODS(100), CURMOD(50), PRMLST(25), VLST(50)
      CHARACTER(LEN=17) :: CALLST(50)
      CHARACTER(LEN=48) ::  DECLFN
      LOGICAL :: LREF(400), EXSTCM, CMCHKD(100)
      INTEGER(2) :: ICLEN
      INTEGER(2) :: ICONF(9999),LN,IBEG,NPRMS,NVS,IFIN,LTYPE,LMAX
      INTEGER IOIN,ITARG,IOOUT,NLINE,ICLOLD,NDSPC,NDALL,NUMMOD
      INTEGER NUMCUR, ITMPF,ITMOD,IMODUL,ITSBR,INTRFC,NUMVAR
      INTEGER IOPTF, NFILES, INTER, KEEP, KPTEMP
!      INTEGER(2) :: IOIN,ITARG,IOOUT,NLINE,ICLOLD,NDSPC,NDALL,NUMMOD
!      INTEGER(2) :: NUMCUR, ITMPF,ITMOD,IMODUL,ITSBR,INTRFC,NUMVAR
!     CALLST IS LIST OF SUBROUTINES/FUNCTIONS CALLED IN PROGRAM UNIT
!     PRMLST IS LIST OF SUBROUTINE OR FUNCTION PARAMETERS
      END MODULE RENCOM
